### ISSUE TITLE
Errors when deleting the folder (Os-Thm Sketchware) + IDEA

### ISSUE THREAD

**Issue by ToastcodeDev** [ThatCakeID/os-thm-android#42]
**.osthm** That is the name of the folder, right? It gives an error when deleting it, so I think it is better that this is through the assets folder, in case you still do not understand I clarify, the application that has the Os-Thm creates an initial folder and This is saved as hidden on the device and if a user sees it they can easily delete it since nowadays people have the option to show hidden files activated, so all I want to tell you is that instead of the folder being hosted in the root of the device because not better in the assets folder.

PD: If the idea is not pleasant they can decline it

**Comment by Iyxan23** [comment]
Just to clarify our themes are now stored on the folder **.os-thm** in the external directory [code](https://github.com/ThatCakeID/os-thm-android/blob/master/lib/src/main/java/tw/osthm/osthmManager.java#L21)

Ok, can you show the error's stacktrace? os-thm is supposed to create / initialize the folder again when it is deleted or not present in the external directory.

For your idea, can you add some details to it? I apologize, I do not really understand what do you mean.

**Comment by ryenyuku** [comment]
Maybe his idea is to save the themes and config file in the assets resources folder. But, other apps can't access that folder and it's read-only. Also deleting the folder won't give me any error as it's reinitialize that folder again, even if you corrupt the config or/and the themes file. os-thm will detect it and deletes them.

**Comment by ToastcodeDev** [comment]
> Maybe his idea is to save the themes and config file in the assets resources folder. But, other apps can't access that folder and it's read-only. Also deleting the folder won't give me any error as it's reinitialize that folder again, even if you corrupt the config or/and the themes file. os-thm will detect it and deletes them.

Before marking as invalid you should see the problem again, **The application gives an error when not detecting the folder!!**

**Comment by ToastcodeDev** [comment]
Repair The Sketchware Proyect Okay!!

**Comment by Iyxan23** [comment]
You should've mention that you're using os-thm-sketchware at the begining, we're a bit confused as there is no problem with the android library.

**Comment by Iyxan23** [comment]
Also you should've posted this issue in [os-thm-sketchware](https://github.com/ThatCakeID/os-thm-sketchware), instead of os-thm-android

**Comment by ToastcodeDev** [comment]
> Also you should've posted this issue in [os-thm-sketchware](https://github.com/ThatCakeID/os-thm-sketchware), instead of os-thm-android

Shhh
