### ISSUE TITLE
Deleting an used theme will crash the app

### ISSUE THREAD

**Issue by ryenyuku** [ThatCakeID/os-thm-android#43]
Deleting an used theme without deleting the folder would make the app crash. Both in os-thm-android and os-thm-sketchware (because basically they're same)

**Comment by ToastcodeDev** [comment]
Exactly what i wanted to explain

**Comment by Iyxan23** [comment]
@ryenyuku Can you get the stacktrace?

**Comment by ryenyuku** [comment]
Fixed in commit 24688de

**Comment by ToastcodeDev** [comment]
> Fixed in commit 24688de

Yes!!
